### ISSUE TITLE
Initial Website Content Plan

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#10]
**Objective**
Devise initial website content

**Description**
Review the contents of the websites such as iheartmob.com and worldbrain.io on mobile and develop content for the website

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Devise website content inventory
- [ ] Write initial content relies on https://github.com/opt-out-tools/theory-of-online-misogyny/issues/21
- [ ] Iterate and add SEO

**Comment by malteserteresa** [comment]
Initial content 
[content.pdf](https://github.com/opt-out-tools/website/files/4040256/content.pdf)
