### ISSUE TITLE
Create professional-looking website design

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/website#9]
**Objective**
Improve the website so it looks professional.

**Description**
Our current website is improving but does not look as professional as it could.

**Skills**
Design

**Tools**
Figma, googledocs

**Time Estimation**

**Tasks**
- [x] Define the Site’s Purpose and Strategy
- [x] Research the Latest Web Design Trends 
- [x] Collect and curate images and ideas
- [ ] Design and developer session
- [ ] Add In and Optimize Content

**Comment by malteserteresa** [comment]
Review of websites:
https://github.com/opt-out-tools/website/wiki/Website-Design-Research

**Comment by lucie-docs** [comment]
@malteserteresa Moving this task to Done too in the repo :)
